spring:
    application:
        name: cars4us
    datasource:
        url: jdbc:postgresql://localhost:5432/cars_4_us
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    liquibase:
        changelog: classpath:db/master-changelog.yaml
